/* ============================================ */
/* Gallery Art Catalog                          */
/* Edit this file to add/remove/reorder art.    */
/* ============================================ */

const GALLERY_ART = [
  // ── Position 0: Bold opener ──
  {
    id: 'img-9635',
    title: 'Untitled IX',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_9635.jpg',
    type: 'image',
    wall: 'left',
    position: 0,
  },
  {
    id: 'iow-1',
    title: 'I Often Wondered I',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/I otten wondered 1.jpeg',
    type: 'image',
    wall: 'right',
    position: 0,
  },
  // ── Position 1: Energy builds ──
  {
    id: 'wthyt',
    title: 'Who The Hell You Talkin',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/who the hell you taljkin.jpeg',
    type: 'image',
    wall: 'left',
    position: 1,
  },
  {
    id: 'img-1720',
    title: 'Untitled IV',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1720.jpg',
    type: 'image',
    wall: 'right',
    position: 1,
  },
  // ── Position 2: Faces in dialogue ──
  {
    id: 'cyhm',
    title: 'Can You Hear Me',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/can you hear me .jpeg',
    type: 'image',
    wall: 'left',
    position: 2,
  },
  {
    id: 'img-5850',
    title: 'Untitled I',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_5850.jpg',
    type: 'image',
    wall: 'right',
    position: 2,
  },
  // ── Position 3: Warm/cool contrast ──
  {
    id: 'img-1703',
    title: 'Untitled II',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1703.jpg',
    type: 'image',
    wall: 'left',
    position: 3,
  },
  {
    id: 'img-1506',
    title: 'Untitled VII',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1506.jpg',
    type: 'image',
    wall: 'right',
    position: 3,
  },
  // ── Position 4: Warmth peak ──
  {
    id: 'img-1498',
    title: 'Untitled VIII',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1498.jpg',
    type: 'image',
    wall: 'left',
    position: 4,
  },
  {
    id: 'iow-2',
    title: 'I Often Wondered II',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/I otten wondered 2.jpeg',
    type: 'image',
    wall: 'right',
    position: 4,
  },
  // ── Position 5: Shift toward abstraction ──
  {
    id: 'notice',
    title: 'Important Notice',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/important notice.jpeg',
    type: 'image',
    wall: 'left',
    position: 5,
  },
  {
    id: 'img-1705',
    title: 'Untitled III',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1705.jpg',
    type: 'image',
    wall: 'right',
    position: 5,
  },
  // ── Position 6: Green harmony ──
  {
    id: 'img-1502',
    title: 'Untitled VI',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1502.jpg',
    type: 'image',
    wall: 'left',
    position: 6,
  },
  {
    id: 'img-8929',
    title: 'Untitled X',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_8929.jpg',
    type: 'image',
    wall: 'right',
    position: 6,
  },
  // ── Position 7: Breathing room ──
  {
    id: 'img-1717',
    title: 'Untitled V',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/IMG_1717.jpg',
    type: 'image',
    wall: 'left',
    position: 7,
  },
  {
    id: 'think',
    title: 'Think You\'d',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/think youd .jpg',
    type: 'image',
    wall: 'right',
    position: 7,
  },
  // ── Position 8: Quiet duality ──
  {
    id: 'flowers',
    title: 'Flowers',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/flowers.jpg',
    type: 'image',
    wall: 'left',
    position: 8,
  },
  {
    id: 'snake',
    title: 'Snake',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/snake.jpg',
    type: 'image',
    wall: 'right',
    position: 8,
  },
  // ── Position 9: Intimate closer ──
  {
    id: 'cyhm-overlay',
    title: 'Can You Hear Me Over All Th',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/CAN You Hear Me over all th.jpg',
    type: 'image',
    wall: 'left',
    position: 9,
  },
];
