/* ============================================ */
/* Gallery Art Catalog                          */
/* Edit this file to add/remove/reorder art.    */
/* ============================================ */

const GALLERY_ART = [
  {
    id: 'iow-1',
    title: 'I Often Wondered I',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/I otten wondered 1.jpeg',
    type: 'image',
    wall: 'left',
    position: 0,
  },
  {
    id: 'iow-2',
    title: 'I Often Wondered II',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/I otten wondered 2.jpeg',
    type: 'image',
    wall: 'right',
    position: 0,
  },
  {
    id: 'cyhm',
    title: 'Can You Hear Me',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/can you hear me .jpeg',
    type: 'image',
    wall: 'left',
    position: 1,
  },
  {
    id: 'wthyt',
    title: 'Who The Hell You Talkin',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/who the hell you taljkin.jpeg',
    type: 'image',
    wall: 'right',
    position: 1,
  },
  {
    id: 'notice',
    title: 'Important Notice',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/important notice.jpeg',
    type: 'image',
    wall: 'left',
    position: 2,
  },
  {
    id: 'think',
    title: 'Think You\'d',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/think youd .jpg',
    type: 'image',
    wall: 'right',
    position: 2,
  },
  {
    id: 'flowers',
    title: 'Flowers',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/flowers.jpg',
    type: 'image',
    wall: 'left',
    position: 3,
  },
  {
    id: 'snake',
    title: 'Snake',
    medium: 'Mixed Media',
    year: '',
    description: '',
    src: 'assets/art/snake.jpg',
    type: 'image',
    wall: 'right',
    position: 3,
  },
];
